// VOUCHERBASE | Parrish Lyon | PL-VOUCHERBASE-20260914
import {cents,money,percent,safeLink,dateOnly} from './ui-utils.js';
const $=id=>document.getElementById(id);
const form=$('analysis-form'), field=name=>form.elements.namedItem(name);
let token='',properties=[],catalog={},analyses=[],jobs=[],lastRecord=null,selectedID=null,selectedSignature='',geoQuality='unverified';
const titles={overview:'Portfolio intelligence',analyze:'Property intelligence',portfolio:'Your property portfolio',evidence:'Evidence & coverage',imports:'Imports & batch jobs'};
const finance=[
 ['purchase_cents','Purchase price ($)','300000','money'],['renovation_cents','Renovation budget ($)','15000','money'],['closing_cents','Acquisition closing costs ($)','6000','money'],['loan_cents','Loan principal ($)','225000','money'],
 ['annual_interest_bps','Annual interest (%)','6.5','bps'],['term_months','Amortization (months)','360','int'],['vacancy_bps','Vacancy (%)','5','bps'],['management_bps','Management / collected rent (%)','8','bps'],
 ['maintenance_bps','Maintenance / collected rent (%)','5','bps'],['annual_tax_cents','Annual property taxes ($)','3000','money'],['annual_insurance_cents','Annual insurance ($)','1800','money'],['monthly_hoa_cents','Monthly HOA ($)','0','money'],['monthly_owner_utilities_cents','Owner-paid utilities / month ($)','0','money'],['monthly_capex_reserve_cents','Capital reserve / month ($)','150','money']
];
const utilities=[['heat_gas','Gas heat'],['heat_electric','Electric heat'],['heat_pump','Heat pump'],['hot_water_gas','Gas hot water'],['hot_water_electric','Electric hot water'],['range_gas','Gas range'],['range_electric','Electric range / microwave'],['other_electric','Other electric / lights / fridge'],['water_sewer','Water & sewer (no septic)'],['water_septic','Water & sewer (with septic)'],['trash','Trash (where applicable)'],['tenant_range','Tenant-supplied range'],['tenant_refrigerator','Tenant-supplied refrigerator']];
function node(tag,text,cls){const n=document.createElement(tag);if(text!==undefined)n.textContent=String(text);if(cls)n.className=cls;return n;}
function setStatus(text,error=false){$('status').textContent=text;$('status').className='status'+(error?' error':'');}
function nav(name){if(!titles[name])return;document.querySelectorAll('.page').forEach(p=>p.hidden=p.id!=='page-'+name);document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===name));$('page-title').textContent=titles[name];window.scrollTo(0,0);}
document.querySelectorAll('[data-page]').forEach(b=>b.addEventListener('click',()=>nav(b.dataset.page)));
for(const [key,label,value,type]of finance){const l=node('label',label);const i=document.createElement('input');i.name=key;i.type='number';i.min='0';i.step=type==='int'?'1':'0.01';i.value=value;if(type==='bps')i.max='100';l.append(i);$('finance-fields').append(l);}
for(const [key,label]of utilities){const l=node('label',undefined,'check');const i=document.createElement('input');i.type='checkbox';i.value=key;i.name='utility';l.append(i,document.createTextNode(label));$('utility-choices').append(l);}
field('effective_on').value=dateOnly();
async function api(path,method='GET',body,extra={}){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),45000);try{const headers={Authorization:'Bearer '+token,...extra};if(body!==undefined && typeof body!=='string')headers['Content-Type']='application/json';const res=await fetch('/api/v1'+path,{method,headers,body:body===undefined?undefined:typeof body==='string'?body:JSON.stringify(body),signal:controller.signal});const data=await res.json();if(!res.ok)throw new Error(data.error||'Request failed');return data;}finally{clearTimeout(timer);}}
async function action(fn){try{setStatus('Working…');await fn();}catch(e){setStatus(e.message||'Operation failed',true);}}
function item(title,description,buttonLabel,fn){const row=node('div',undefined,'list-item'),copy=node('div');copy.append(node('strong',title),node('p',description));row.append(copy);if(fn){const b=node('button',buttonLabel,'secondary');b.type='button';b.addEventListener('click',()=>action(fn));row.append(b);}return row;}
function empty(el,text){el.replaceChildren(node('p',text,'empty'));}
function link(url,text='Open source'){const u=safeLink(url);if(!u)return node('span','No source URL');const a=node('a',text);a.href=u;a.target='_blank';a.rel='noopener noreferrer';return a;}
async function refresh(){[properties,catalog,analyses,jobs]=await Promise.all([api('/properties'),api('/catalog'),api('/analyses'),api('/jobs')]);const audit=await api('/audit');$('count-properties').textContent=properties.length;$('count-analyses').textContent=analyses.length;$('count-sources').textContent=(catalog.sources||[]).length;
 const current=field('authority_id').value;$('authority-select').replaceChildren(new Option('Unknown / not selected',''));for(const a of catalog.authorities||[]){if(a.id!=='HUD')$('authority-select').append(new Option(a.name,a.id));}field('authority_id').value=current;
 renderPortfolio();renderJobs();renderEvidence(audit);const recent=$('recent-analyses');recent.replaceChildren();if(!analyses.length)empty(recent,'No analyses yet. Start with the demonstration property or enter your own.');for(const a of analyses.slice(0,5))recent.append(item(a.address,`Effective ${a.effective_on} · ${a.id.slice(0,8)}`,'View',()=>openAnalysis(a.id)));}
$('login-form').addEventListener('submit',async e=>{e.preventDefault();token=$('api-token').value.trim();$('login-error').textContent='';try{const me=await api('/me');$('account-label').textContent=me.label+' / '+me.role;$('demo-badge').textContent=me.demo_enabled?'Demo fixtures enabled · labeled':'Live-data workspace';$('load-demo').hidden=!me.demo_enabled;await refresh();$('login').hidden=true;$('workspace').hidden=false;$('api-token').value='';setStatus('Workspace ready. Select a property or load the demo.');}catch(err){token='';$('login-error').textContent=err.message;}});
$('logout').addEventListener('click',()=>{token='';properties=[];lastRecord=null;$('workspace').hidden=true;$('login').hidden=false;$('analysis-results').hidden=true;});
$('refresh').addEventListener('click',()=>action(async()=>{await refresh();setStatus('Workspace refreshed.');}));
function formProperty(){const lat=field('latitude').value,lon=field('longitude').value;const demo=field('is_demo').checked;return{address:field('address').value.trim(),city:field('city').value.trim(),state:field('state').value.trim().toUpperCase(),zip:field('zip').value.trim(),bedrooms:Number(field('bedrooms').value),bathrooms:Number(field('bathrooms').value),sqft:Number(field('sqft').value),structure:field('structure').value,condition:field('condition').value,amenities:field('amenities').value.split(',').map(v=>v.trim()).filter(Boolean),latitude:lat===''?null:Number(lat),longitude:lon===''?null:Number(lon),geocode_status:lat===''?'unverified':demo?'synthetic':geoQuality==='unverified'?'user_confirmed':geoQuality,is_demo:demo};}
function fillProperty(p){for(const key of ['address','city','state','zip','bedrooms','bathrooms','sqft','structure','condition'])field(key).value=p[key];field('amenities').value=(p.amenities||[]).join(', ');field('latitude').value=p.latitude??'';field('longitude').value=p.longitude??'';field('is_demo').checked=p.is_demo;geoQuality=p.geocode_status;$('geocode-state').textContent=geoQuality;selectedID=p.id;selectedSignature=JSON.stringify(formProperty());nav('analyze');}
$('load-demo').addEventListener('click',()=>action(async()=>{const p=properties.find(p=>p.is_demo);if(!p)throw new Error('Demo property not seeded. Check VB_DEMO and bootstrap.');fillProperty(p);field('authority_id').value='DEMO';field('authority_confirmed').checked=true;field('utilities_complete').checked=true;field('comparable_kind').value='synthetic';field('knowledge_at').value='';field('effective_on').value=dateOnly();document.querySelectorAll('input[name=utility]').forEach(i=>i.checked=['heat_gas','other_electric','water_sewer'].includes(i.value));setStatus('Loaded a synthetic property, schedule and comparable sample. Not a real rental estimate.');}));
for(const key of ['address','city','state','zip'])field(key).addEventListener('input',()=>{field('latitude').value='';field('longitude').value='';geoQuality='unverified';$('geocode-state').textContent='Address changed; geocoding must be repeated';});
for(const key of ['latitude','longitude'])field(key).addEventListener('input',()=>{geoQuality='user_confirmed';$('geocode-state').textContent='User-entered coordinates';});
let matches=[];
function useMatch(m){field('latitude').value=m.latitude;field('longitude').value=m.longitude;geoQuality=m.quality;$('geocode-state').textContent=m.warning;}
$('geocode').addEventListener('click',()=>action(async()=>{const address=[field('address').value,field('city').value,field('state').value,field('zip').value].join(', ').replace(', CO,',', CO');const provider=field('is_demo').checked?'fixture':'census';if(provider==='census'&&!confirm('When enabled, this sends the address to the US Census Geocoder. Continue?')){setStatus('Geocoding cancelled.');return;}const out=await api('/geocode','POST',{address,provider});matches=out.matches||[];const select=$('geocode-matches');select.replaceChildren(new Option('Select the correct match',''));matches.forEach((m,i)=>select.append(new Option(m.address,String(i))));select.hidden=matches.length<2;if(matches.length===1)useMatch(matches[0]);$('geocode-state').textContent=out.warning||out.status;if(matches.length===1)$('geocode-state').textContent=matches[0].warning;setStatus(matches.length?`${matches.length} geocoding match(es). Confirm the address and authority.`:(out.warning||'No match; no coordinates were fabricated.'));}));
$('geocode-matches').addEventListener('change',e=>{if(e.target.value!=='')useMatch(matches[Number(e.target.value)]);});
function requestFor(propertyID){const underwriting=field('enable_underwriting').checked?Object.fromEntries(finance.map(([key,,,type])=>[key,type==='int'?Number(field(key).value):cents(field(key).value)])):null;const rent=field('rent').value===''?null:cents(field('rent').value);return{property_id:propertyID,effective_on:field('effective_on').value,knowledge_at:field('knowledge_at').value.trim(),authority_id:field('authority_id').value,authority_confirmed:field('authority_confirmed').checked,voucher_bedrooms:field('voucher_bedrooms').value===''?null:Number(field('voucher_bedrooms').value),utilities:{complete:field('utilities_complete').checked,items:[...document.querySelectorAll('input[name=utility]:checked')].map(i=>i.value)},proposed_rent_cents:rent,underwriting,scenarios:underwriting&&rent!==null?[{name:'Rent −5%',rent_cents:Math.round(rent*.95),vacancy_bps:null,renovation_cents:null},{name:'Vacancy 10%',rent_cents:null,vacancy_bps:1000,renovation_cents:null},{name:'Renovation +20%',rent_cents:null,vacancy_bps:null,renovation_cents:Math.round(underwriting.renovation_cents*1.2)}]:[],comparable_kind:field('comparable_kind').value,benchmark_entity:field('benchmark_entity').value.trim()};}
form.addEventListener('submit',e=>{e.preventDefault();if(!form.reportValidity())return;action(async()=>{const btn=$('analyze-submit');btn.disabled=true;try{requestFor('validation');const p=formProperty();let id=selectedID;if(!id||JSON.stringify(p)!==selectedSignature){const saved=await api('/properties','POST',p);id=saved.id;selectedID=id;selectedSignature=JSON.stringify(p);}const out=await api('/analyses','POST',requestFor(id),{'Idempotency-Key':crypto.randomUUID()});renderResults(out);await refresh();setStatus('Analysis saved with source references and calculation version.');$('analysis-results').scrollIntoView({behavior:'smooth'});}finally{btn.disabled=false;}});});
function metric(title,value,note){const a=node('article');a.append(node('span',title),node('strong',value),node('small',note));return a;}
function renderResults(record){lastRecord=record;const r=record.result,c=r.calculation,m=r.market;$('analysis-results').hidden=false;$('result-address').textContent=r.property.address+', '+r.property.city;$('result-date').textContent=`Effective ${record.effective_on||record.input?.effective_on} · ${record.id} · ${r.property.is_demo?'SYNTHETIC DEMO':'Property planning'}`;const warnings=[...new Set([...(r.warnings||[]),...(c.warnings||[])])];$('result-warnings').replaceChildren(...warnings.map(t=>node('span',t.replaceAll('_',' '),'warning-item')));$('result-metrics').replaceChildren(metric('Published / applicable standard',money(c.payment_standard_cents),'Not guaranteed owner payment'),metric('Tenant utility allowance',money(c.utility_allowance_cents),'Unknown is not zero'),metric('Planning contract reference',money(c.planning_contract_reference_cents),'Standard less utility allowance'),metric('Comparable-market median',money(m.median_cents),m.kind||'Evidence unavailable'));
 const dl=$('calculation-lines');dl.replaceChildren();for(const [k,v]of [['Standard basis',c.payment_standard_basis],['Proposed gross rent',money(c.proposed_gross_rent_cents)],['Gross amount above standard',money(c.gross_above_standard_cents)],['PHA approval','Not obtained'],['Household subsidy','Not calculated'],['Utility bedroom category',r.utility_bedrooms]])dl.append(node('dt',k),node('dd',v));
 const ms=$('market-summary');ms.replaceChildren(node('p',m.status.replaceAll('_',' '),'market-kind'),node('div',m.range_cents?m.range_cents.map(money).join(' – '):'Insufficient evidence','money-range'),node('p',`${m.selected?.length||0} selected observations · ${m.kind||'unknown type'}`));
 const cf=$('cashflow-body');cf.replaceChildren();for(const f of c.cashflows||[]){const tr=node('tr');[f.name,money(f.rent_cents),money(f.annual_noi_cents),money(f.annual_cashflow_cents),percent(f.cash_on_cash_bps),f.dscr_milli==null?'N/A':(f.dscr_milli/1000).toFixed(3)].forEach((v,i)=>tr.append(node('td',v,i===3?(f.annual_cashflow_cents<0?'negative':'positive'):undefined)));cf.append(tr);}if(!(c.cashflows||[]).length){const tr=node('tr'),td=node('td','No cash-flow scenario: a proposed rent and complete financial assumptions are required.');td.colSpan=6;tr.append(td);cf.append(tr);}
 const cb=$('comp-body');cb.replaceChildren();for(const comp of m.selected||[]){const tr=node('tr');for(const v of [comp.property_ref,money(comp.rent_cents),comp.kind,Math.round(comp.distance_m)+' m',comp.observed_on])tr.append(node('td',v));const td=node('td');td.append(link(comp.source_url));tr.append(td);cb.append(tr);}
 const src=$('result-sources');src.replaceChildren();const unique=[...new Map([...(r.sources||[]),...(r.benchmarks||[])].map(s=>[s.source_id,s])).values()];if(!unique.length)empty(src,'No applicable official schedule was selected. No source is being implied.');for(const s of unique)src.append(item(s.title,`${s.category} · effective ${s.valid_from} · source ${s.source_id.slice(0,8)}`,'Inspect',()=>showSource(s.source_id)));
 $('result-hash').textContent=`Record SHA-256: ${record.result_sha256} | ${c.engine_version} | ${r.watermark}`;
}
async function openAnalysis(id){const out=await api('/analyses/'+id);renderResults(out);nav('analyze');$('analysis-results').scrollIntoView({behavior:'smooth'});setStatus('Loaded the saved snapshot. It has not been updated with newer data.');}
function renderPortfolio(){const body=$('portfolio-body');body.replaceChildren();for(const p of properties){const tr=node('tr'),sel=node('td'),cb=document.createElement('input');cb.type='checkbox';cb.value=p.id;cb.name='portfolio-select';cb.setAttribute('aria-label','Select '+p.address);sel.append(cb);tr.append(sel);const c=p.latest_result?.calculation,m=p.latest_result?.market;for(const v of [p.address+(p.is_demo?' · DEMO':''),p.bedrooms,money(c?.planning_contract_reference_cents),money(m?.median_cents),money(c?.cashflows?.[0]?.annual_cashflow_cents)])tr.append(node('td',v));const td=node('td'),edit=node('button','Use property','secondary');edit.addEventListener('click',()=>fillProperty(p));td.append(edit);if(p.latest_analysis_id){const v=node('button','View analysis','secondary');v.addEventListener('click',()=>action(()=>openAnalysis(p.latest_analysis_id)));td.append(v);}tr.append(td);body.append(tr);}}
$('batch-selected').addEventListener('click',()=>action(async()=>{const ids=[...document.querySelectorAll('input[name=portfolio-select]:checked')].map(i=>i.value);if(!ids.length)throw new Error('Select at least one property.');if(!confirm(`Apply the current analysis-form assumptions to ${ids.length} properties?`)){setStatus('Batch cancelled.');return;}const out=await api('/jobs','POST',{items:ids.map(requestFor)},{'Idempotency-Key':crypto.randomUUID()});nav('imports');await refresh();setStatus('Queued batch '+out.id+'. Refresh to track progress.');}));
async function showSource(id){const s=await api('/sources/'+id);$('dialog-title').textContent=s.title;$('dialog-content').textContent=JSON.stringify(s,null,2);$('source-dialog').showModal();setStatus('Source snapshot opened.');}
$('close-dialog').addEventListener('click',()=>$('source-dialog').close());
function renderEvidence(audit){$('coverage-summary').textContent=catalog.coverage;$('source-list').replaceChildren();for(const s of catalog.sources||[])$('source-list').append(item(s.title,`${s.category.toUpperCase()} · retrieved ${new Date(s.retrieved_at).toLocaleDateString()} · ${s.reviewed_by||'Pending named review'}`,'Inspect',()=>showSource(s.id)));$('catalog-changes').replaceChildren();for(const c of (catalog.changes||[]).slice(0,10))$('catalog-changes').append(item(c.event,new Date(c.created_at).toLocaleString()));$('audit-list').replaceChildren();for(const a of audit.slice(0,20))$('audit-list').append(item(a.action,`${new Date(a.occurred_at).toLocaleString()} · ${a.object_id}`));}
function renderJobs(){const el=$('job-list');el.replaceChildren();if(!jobs.length)empty(el,'No batch jobs yet. Select saved properties on the Portfolio page.');for(const j of jobs)el.append(item(j.id.slice(0,8),`${j.complete}/${j.total} complete · ${j.queued} queued · ${j.running} running · ${j.failed} failed`,'Details',async()=>{const details=await api('/jobs/'+j.id);$('dialog-title').textContent='Batch '+j.id;$('dialog-content').textContent=JSON.stringify(details,null,2);$('source-dialog').showModal();setStatus('Batch details opened.');}));}
function download(content,name,type){const b=new Blob([content],{type});const url=URL.createObjectURL(b);const a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
$('export-result').addEventListener('click',()=>{if(lastRecord)download(JSON.stringify(lastRecord,null,2),'voucherbase-'+lastRecord.id+'.json','application/json');});
$('print-result').addEventListener('click',()=>window.print());
$('replay-result').addEventListener('click',()=>action(async()=>{if(!lastRecord)return;const out=await api('/analyses/'+lastRecord.id+'/replay','POST',{});setStatus(out.matched?'Replay matched: identical saved inputs produced the same calculation hash.':'Replay differs: check the engine version before relying on this result.',!out.matched);}));
$('import-properties').addEventListener('click',()=>action(async()=>{const f=$('property-file').files[0];if(!f)throw new Error('Choose a property CSV file.');if(f.size>2_000_000)throw new Error('File exceeds 2 MB.');const out=await api('/imports/properties','POST',await f.text(),{'Content-Type':'text/csv'});await refresh();setStatus(`Imported ${out.imported} properties. Nothing was geocoded externally.`);}));
$('import-comparables').addEventListener('click',()=>action(async()=>{const f=$('comparable-file').files[0];if(!f)throw new Error('Choose a comparable JSON file.');if(f.size>2_000_000)throw new Error('File exceeds 2 MB.');const body=JSON.parse(await f.text());const out=await api('/comparables','POST',body);await refresh();setStatus(`Imported ${out.imported} observations with source references.`);}));
setInterval(async()=>{if(token&&!$('page-imports').hidden&&jobs.some(j=>j.queued||j.running)){try{jobs=await api('/jobs');renderJobs();}catch{setStatus('Job refresh failed. Use Refresh to retry.',true);}}},5000);
